### ISSUE TITLE
How to choose the normalization process with RUVg

### ISSUE THREAD

**Issue by fatyang799** [drisso/RUVSeq#3]
Dear @drisso 

I am learning the RUVg package in R following the tutorial published in bioconductor. It is really user friendly and I can understand the tutorial without much difficulty. I really appreciate your work about it. However, there are some issues I am still a little confused.

I notice that in the tutorial, before you performed the RUVg normalization, you did the UQ normalization. The RUVg was performed based on the data normalized by UQ. As far as I know, since the UQ and RUVg are both normalization methods, they do the similar thing to normalize the data. So I wonder is UQ normalization necessary? After all, when I do the UQ normalization, the normalizedCounts in assayData slot of SeqExpressionSet object was filled. Then after I do RUVg normalization, the normalizedCounts in assayData slot of SeqExpressionSet object was overwrited. And these normalizedCounts values are different. So I try 2 different process to do the RUVg. Below is my code in R:

```R
# prepare data for analysis
if (T) {
    x <- as.factor(rep(c("Ctl", "Trt"), each=3))
    set <- newSeqExpressionSet(as.matrix(filtered),
                               phenoData = data.frame(x, row.names=colnames(filtered)))
    uq_set <- betweenLaneNormalization(set, which="upper")
}
# RUVg to normalization
if (T) {
  # according to the tutorial in bioconductor
  if (T) {
    ruvg_uq_set <- RUVg(x=uq_set, cIdx=spikes, k=1)
    pData(ruvg_uq_set)
    #         x         W_1
	# Ctl1  Ctl -0.04539413
	# Ctl3  Ctl  0.50347642
	# Ctl5  Ctl  0.40575319
	# Trt9  Trt -0.30773479
	# Trt11 Trt -0.68455406
	# Trt13 Trt  0.12845337
  }
  
  # perform RUVg on rawdata
  if (T) {
    ruvg_set <- RUVg(x=set, cIdx=spikes, k=1)
    pData(ruvg_set)
    #         x        W_1
	# Ctl1  Ctl -0.0390975
	# Ctl3  Ctl  0.4088907
	# Ctl5  Ctl  0.4414666
	# Trt9  Trt -0.2138095
	# Trt11 Trt -0.7527070
	# Trt13 Trt  0.1552567
  }
}
```

The results are different. And since the estimated factors of unwanted are used in the downstream DEG analysis. So I am confuse about the fact which process should I choose to follow.

Could you please help me to figure them out? Or just give me some suggestions if possible? Thank you very much. I will be appreciated for your reply, thank you very much!

Best regards,

Yang Liu

**Comment by drisso** [comment]
Hi Yang Liu,

sorry for the very late reply. I hope this is still useful.

As we explain in [our paper](https://www.nature.com/articles/nbt.2931), a UQ normalization step prior to RUV is helpful. This is because UQ will scale the counts to have their distributions roughly comparable and then the RUV factors can capture the rest of the unwanted variation present in the data.

It is not strictly necessary to run RUV on UQ-normalized data, when running it on unnormalized data, usually the first factor captures sequencing depth, hence RUV on normalized data with k factors is usually similar to RUV on unnormalized data with k+1 factors.

I hope this helps.

Best,
Davide
